name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: check
        run : echo "${{ env.DOCKER_PASSWORD }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Docker login
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USER --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{env.DOCKER_USER}}/hackathon:latest

      - name: Docker push
        run: docker push ${{env.DOCKER_USER}}/hackathon:latest

      - name: Redeploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd hackathon/
            docker compose pull 
            docker compose up -d
            docker image prune -f